services:
  postgres:
    image: postgres:16-alpine
    container_name: ecom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: ecom-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ecom_orders
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  meilisearch:
    image: getmeili/meilisearch:v1.37
    container_name: ecom-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterkey_for_dev_only}
      MEILI_ENV: ${MEILI_ENV:-development}
    ports:
      - '7700:7700'
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  mongo_data:
  meilisearch_data:
